### importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### importing data set

In [11]:

dataset = pd.read_csv('Wholesale customers data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
print(x)

[[    2 12669  9656 ...   214  2674  1338]
 [    2  7057  9810 ...  1762  3293  1776]
 [    2  6353  8808 ...  2405  3516  7844]
 ...
 [    2 14531 15488 ...   437 14841  1867]
 [    1 10290  1981 ...  1038   168  2125]
 [    1  2787  1698 ...    65   477    52]]


In [7]:
print(y)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


### taking care of missing data

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [14]:
print(x)

[[    2 12669  9656 ...   214  2674  1338]
 [    2  7057  9810 ...  1762  3293  1776]
 [    2  6353  8808 ...  2405  3516  7844]
 ...
 [    2 14531 15488 ...   437 14841  1867]
 [    1 10290  1981 ...  1038   168  2125]
 [    1  2787  1698 ...    65   477    52]]


### encoding categorical data

### encoding categorical data

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [16]:
print(x)

[[0.0000e+00 1.0000e+00 1.2669e+04 ... 2.1400e+02 2.6740e+03 1.3380e+03]
 [0.0000e+00 1.0000e+00 7.0570e+03 ... 1.7620e+03 3.2930e+03 1.7760e+03]
 [0.0000e+00 1.0000e+00 6.3530e+03 ... 2.4050e+03 3.5160e+03 7.8440e+03]
 ...
 [0.0000e+00 1.0000e+00 1.4531e+04 ... 4.3700e+02 1.4841e+04 1.8670e+03]
 [1.0000e+00 0.0000e+00 1.0290e+04 ... 1.0380e+03 1.6800e+02 2.1250e+03]
 [1.0000e+00 0.0000e+00 2.7870e+03 ... 6.5000e+01 4.7700e+02 5.2000e+01]]


### encodin gdependent variable

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
print(y)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


### splitting dataset into train data and test data

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 1)

In [20]:
print(x_train)

[[1.0000e+00 0.0000e+00 3.9228e+04 ... 4.5100e+03 9.3000e+01 2.3460e+03]
 [0.0000e+00 1.0000e+00 2.1370e+03 ... 1.2740e+03 1.7120e+04 1.4200e+02]
 [1.0000e+00 0.0000e+00 7.0050e+03 ... 4.3000e+02 6.1000e+02 5.2900e+02]
 ...
 [0.0000e+00 1.0000e+00 4.5150e+03 ... 2.6440e+03 3.3780e+03 2.2130e+03]
 [1.0000e+00 0.0000e+00 1.8380e+03 ... 1.2180e+03 1.2160e+03 2.9500e+02]
 [0.0000e+00 1.0000e+00 1.5168e+04 ... 1.9200e+03 6.5060e+03 7.1400e+02]]


In [21]:
print(x_test)

[[1.0000e+00 0.0000e+00 2.5767e+04 3.6130e+03 2.0130e+03 1.0303e+04
  3.1400e+02 1.3840e+03]
 [1.0000e+00 0.0000e+00 6.2110e+03 3.3700e+02 6.8300e+02 1.0890e+03
  4.1000e+01 2.9600e+02]
 [0.0000e+00 1.0000e+00 2.5410e+03 4.7370e+03 6.0890e+03 2.9460e+03
  5.3160e+03 1.2000e+02]
 [0.0000e+00 1.0000e+00 1.6448e+04 6.2430e+03 6.3600e+03 8.2400e+02
  2.6620e+03 2.0050e+03]
 [1.0000e+00 0.0000e+00 8.6070e+03 1.7500e+03 3.5800e+03 4.7000e+01
  8.4000e+01 2.5010e+03]
 [1.0000e+00 0.0000e+00 2.6400e+04 1.3770e+03 4.1720e+03 8.3000e+02
  9.4800e+02 1.2180e+03]
 [0.0000e+00 1.0000e+00 4.4466e+04 5.4259e+04 5.5571e+04 7.7820e+03
  2.4171e+04 6.4650e+03]
 [1.0000e+00 0.0000e+00 3.5210e+03 1.0990e+03 1.9970e+03 1.7960e+03
  1.7300e+02 9.9500e+02]
 [1.0000e+00 0.0000e+00 2.5962e+04 1.7800e+03 3.8380e+03 6.3800e+02
  2.8400e+02 8.3400e+02]
 [0.0000e+00 1.0000e+00 2.2615e+04 5.4100e+03 7.1980e+03 3.9150e+03
  1.7770e+03 5.1850e+03]
 [1.0000e+00 0.0000e+00 1.0290e+04 1.9810e+03 2.2320e+03 1.0380e+03
  

In [22]:
print(y_train)

[2 1 2 2 2 2 2 2 0 1 2 2 2 2 1 2 2 0 2 2 1 2 2 0 2 2 2 2 2 2 1 2 2 2 2 0 0
 2 2 2 2 0 2 2 1 1 0 0 2 2 2 1 2 2 1 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 1 0 0
 2 2 2 1 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 1 2 0 2 2 2 2 2 2 2 0 2 2 1 0 2
 2 2 2 1 1 2 2 2 0 2 0 2 0 2 1 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 1 2 1 1
 2 2 0 2 2 2 2 2 1 2 2 2 2 2 2 2 0 2 2 1 2 2 1 2 2 1 2 2 2 0 0 2 2 2 0 1 2
 0 0 2 2 2 0 2 2 0 2 2 2 0 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 0 2 2 2 0 2 1 2
 2 2 2 2 0 2 2 2 0 2 0 0 2 1 1 2 2 2 2 2 0 2 0 2 2 2 2 2 0 0 0 1 1 2 2 2 1
 2 2 2 0 2 2 0 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 0 2 2 1 2 2 1 1 2
 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 1 2 2 1 2 1 1 2 2 2 2 2 0 0 2 2 2 2 2 0 2 2
 2 0 2 2 2 2 0 2 2 2 1 2 0 2 0 2 2 0 2]


In [23]:
print(y_test)

[2 2 0 1 2 2 2 2 0 2 2 2 2 2 0 1 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 0 2 1 0 2 2
 2 2 2 0 2 2 0 2 2 2 2 2 2 2 1 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 1 2 0 2 2 0
 2 1 0 2 2 0 2 2 2 2 2 2 0 0]


### feature scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [25]:
print(x_train)

[[ 1.00000000e+00  0.00000000e+00  3.92280000e+04 ...  2.68073365e-01
  -5.81901185e-01  2.65866524e-01]
 [ 0.00000000e+00  1.00000000e+00  2.13700000e+03 ... -3.55965840e-01
   2.96761527e+00 -4.54561329e-01]
 [ 1.00000000e+00  0.00000000e+00  7.00500000e+03 ... -5.18725139e-01
  -4.74125300e-01 -3.28061520e-01]
 ...
 [ 0.00000000e+00  1.00000000e+00  4.51500000e+03 ... -9.17712448e-02
   1.02903040e-01  2.22392429e-01]
 [ 1.00000000e+00  0.00000000e+00  1.83800000e+03 ... -3.66765036e-01
  -3.47796118e-01 -4.04549777e-01]
 [ 0.00000000e+00  1.00000000e+00  1.51680000e+04 ... -2.31389411e-01
   7.54978418e-01 -2.67590035e-01]]


In [26]:
print(x_test)

[[ 1.00000000e+00  0.00000000e+00  2.57670000e+04 -3.00043784e-01
  -6.21572103e-01  1.38521153e+00 -5.35830642e-01 -4.85851980e-02]
 [ 1.00000000e+00  0.00000000e+00  6.21100000e+03 -7.42002333e-01
  -7.60317185e-01 -3.91641753e-01 -5.92741313e-01 -4.04222904e-01]
 [ 0.00000000e+00  1.00000000e+00  2.54100000e+03 -1.48407212e-01
  -1.96365368e-01 -3.35327281e-02  5.06906263e-01 -4.61752533e-01]
 [ 0.00000000e+00  1.00000000e+00  1.64480000e+04  5.47642090e-02
  -1.68094753e-01 -4.42745087e-01 -4.63571810e-02  1.54402868e-01]
 [ 1.00000000e+00  0.00000000e+00  8.60700000e+03 -5.51377354e-01
  -4.58103272e-01 -5.92583920e-01 -5.83777361e-01  3.16531822e-01]
 [ 1.00000000e+00  0.00000000e+00  2.64000000e+04 -6.01698032e-01
  -3.96346062e-01 -4.41588031e-01 -4.03664469e-01 -1.02846098e-01]
 [ 0.00000000e+00  1.00000000e+00  4.44660000e+04  6.53250588e+00
   4.96557763e+00  8.99054910e-01  4.43749490e+00  1.61225596e+00]
 [ 1.00000000e+00  0.00000000e+00  3.52100000e+03 -6.39202451e-01
  -