### perceptron


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Load dataset
dataset = pd.read_csv('Wholesale customers data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### splitting dataset into training set and test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[    2 24653  9465 ...   294  5058  2168]
 [    1   444   879 ...   264   290   259]
 [    1 22686   134 ...  3157     9   548]
 ...
 [    1  6990  3880 ...  1647   319  1160]
 [    2 44466 54259 ...  7782 24171  6465]
 [    1   955  5479 ...   333  2840   707]]


In [8]:
print(y_train)

[3 2 3 1 1 1 3 3 3 1 3 2 2 3 3 3 3 3 3 3 3 3 1 3 1 3 3 3 3 2 3 3 1 3 3 1 1
 1 3 3 3 3 3 1 3 3 3 1 3 3 3 3 3 3 3 3 3 1 3 3 3 3 1 3 3 3 3 3 3 2 3 3 3 2
 1 3 3 2 2 3 3 3 3 3 1 3 3 3 3 1 3 3 1 3 3 1 3 3 3 3 3 3 3 3 3 3 1 3 3 2 2
 3 3 3 1 3 3 3 2 3 1 3 3 3 1 3 2 3 2 1 3 3 1 3 1 1 1 2 1 1 3 3 2 1 3 3 1 3
 3 3 3 3 2 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 2 3 2 3 1 1 2 3 1 3 3 1 1 2 3 2 3
 3 3 3 3 3 3 3 2 3 3 3 3 2 1 3 2 3 1 3 3 3 3 1 3 1 3 3 3 3 1 3 3 3 3 3 3 3
 1 3 3 2 3 3 1 3 3 3 3 3 3 2 3 3 1 3 1 3 3 2 3 3 3 3 1 2 1 3 3 3 3 3 3 1 3
 3 3 3 2 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 2
 2 1 1 3 3 1 3 2 3 3 2 3 3 3 3 3 2 3 3 3 3 3 1 3 1 3 3 3 1 2 3 3 3 3]


In [9]:
print(X_test)

[[    1  1537  3748  5838  1859  3381   806]
 [    2  5981 14641 20521  2005 12218   445]
 [    1  8040  3795  2070  6340   918   291]
 [    2  9759 25071 17645  1128 12408  1625]
 [    1 27329  1449  1947  2436   204  1333]
 [    2 31714 12319 11757   287  3881  2931]
 [    2   355  7704 14682   398  8077   303]
 [    1 68951  4411 12609  8692   751  2406]
 [    1   894  1703  1841   744   759  1153]
 [    1 11800  2713  3558  2121   706    51]
 [    2  3366  5403 12974  4400  5977  1744]
 [    2  1107 11711 23596   955  9265   710]
 [    1  1206  3620  2857  1945   353   967]
 [    1 25767  3613  2013 10303   314  1384]
 [    1  7858  1110  1094  6818    49   287]
 [    1  2787  1698  2510    65   477    52]
 [    2 15168 10556 12477  1920  6506   714]
 [    2    23  2616  8118   145  3874   217]
 [    1 27167  2801  2128 13223    92  1902]
 [    1 37036  7152  8253  2995    20     3]
 [    1 32717 16784 13626 60869  1272  5609]
 [    2   200 25862 19816   651  8773  6250]
 [    1 11

In [10]:
print(y_test)

[1 3 1 2 3 3 3 3 3 2 3 1 3 3 1 3 3 3 3 3 2 3 1 1 3 3 1 2 3 1 3 3 3 3 2 3 3
 3 3 2 3 3 3 3 3 3 3 1 3 3 3 1 1 3 3 3 3 3 3 3 2 3 3 3 3 2 3 3 3 3 3 3 3 3
 1 1 3 3 3 3 3 3 2 3 3 3 3 3 3 1 3 1 3 3 1 3 2 3 3 1 3 3 1 3 3 3 2 3 3 2]


### feature scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[ 1.49509000e+00  9.97642094e-01  4.49837762e-01 ... -6.34194775e-01
   4.46433114e-01  1.71158290e-01]
 [-6.68856054e-01 -9.13450827e-01 -6.47498296e-01 ... -6.41189087e-01
  -5.18901958e-01 -4.31540312e-01]
 [-6.68856054e-01  8.42364314e-01 -7.42713223e-01 ...  3.32957520e-02
  -5.75793560e-01 -3.40298879e-01]
 ...
 [-6.68856054e-01 -3.96700269e-01 -2.63954677e-01 ... -3.18751295e-01
  -5.13030583e-01 -1.47081726e-01]
 [ 1.49509000e+00  2.56170852e+00  6.17474708e+00 ...  1.11158555e+00
   4.31607431e+00  1.52778265e+00]
 [-6.68856054e-01 -8.73111759e-01 -5.95940488e-02 ... -6.25102169e-01
  -2.62586060e-03 -2.90100305e-01]]


In [13]:
print(X_test)

[[-6.68856054e-01 -8.27167851e-01 -2.80824973e-01 -2.28190973e-01
  -2.69324822e-01  1.06905657e-01 -2.58844589e-01]
 [ 1.49509000e+00 -4.76352165e-01  1.11135785e+00  1.23042639e+00
  -2.35285836e-01  1.89605541e+00 -3.72817452e-01]
 [-6.68856054e-01 -3.13811774e-01 -2.74818125e-01 -6.02506183e-01
   7.75392276e-01 -3.91756316e-01 -4.21437454e-01]
 [ 1.49509000e+00 -1.78111467e-01  2.44436682e+00  9.44722954e-01
  -4.39752896e-01  1.93452304e+00 -2.74575772e-04]
 [-6.68856054e-01  1.20888934e+00 -5.74649291e-01 -6.14725071e-01
  -1.34800884e-01 -5.36313623e-01 -9.24631519e-02]
 [ 1.49509000e+00  1.55504749e+00  8.14594006e-01  3.59805769e-01
  -6.35826781e-01  2.08136264e-01  4.12048302e-01]
 [ 1.49509000e+00 -9.20476613e-01  2.24772679e-01  6.50376891e-01
  -6.09947826e-01  1.05766352e+00 -4.17648883e-01]
 [-6.68856054e-01  4.49458927e+00 -1.96090078e-01  4.44443922e-01
   1.32374635e+00 -4.25567338e-01  2.46298294e-01]
 [-6.68856054e-01 -8.77927186e-01 -5.42186752e-01 -6.25255170e-0

### training perceptron model in to dataset

In [14]:
# Train Perceptron model
from sklearn.linear_model import Perceptron
classifier = Perceptron(max_iter=1000, tol=1e-3, random_state=0)
classifier.fit(X_train, y_train)

Perceptron()

### predicting a new result

In [15]:
# Predict for a new sample
print(classifier.predict(sc.transform([[30,87000,0,0,0,0,0]])))

[2]


### predcting test set results

In [16]:
# Predict on test set
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 1]
 [3 3]
 [3 1]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 2]
 [3 3]
 [3 1]
 [3 1]
 [3 3]
 [3 3]
 [3 1]
 [3 2]
 [2 3]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 1]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 1]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 1]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 2]]


### making confusion matrix

In [19]:
# Evaluate model
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f'Accuracy: {accuracy_score(y_test, y_pred):.2f}')

[[ 0  0 18]
 [ 1  0 11]
 [ 0  1 79]]
Accuracy: 0.72


In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import Perceptron
# from sklearn.metrics import accuracy_score

# # Load dataset
# dataset = pd.read_csv('Wholesale customers data.csv')
# X = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, -1].values

# # Split dataset
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# # Train Perceptron model
# classifier = Perceptron(max_iter=1000, tol=1e-3, random_state=0)
# classifier.fit(X_train, y_train)

# # Predictions
# y_pred = classifier.predict(X_test)

# # Evaluate model
# accuracy = accuracy_score(y_test, y_pred)
# print(f'Perceptron Model Accuracy: {accuracy:.2f}')


Perceptron Model Accuracy: 0.53
